export const EVENTS = Object.freeze({
  DB_CONNECT: "db:connect",
  DB_FETCH_DB: "db:fetchDatabases",
  DB_DATABASES_SELECTED: "db:databaseSelected",
  DB_DATABASES_LOADED: "db:databasesLoaded",
  DB_COLLECTIONS_SELECTED: "db:collectionSelected",
  DB_COLLECTIONS_LOADED: "db:collectionsLoaded",
  QUERY_RESULT: "query:result",
  QUERY_SEND: "query:send",
  QUERY_ERROR: "query:error",
  RECORD_UPDATE: "record:update",
  RECORD_INSERT: "record:insert",
  TOAST_SHOW: "show:toast",
  RECORD_DELETE: "delete:record",
  RECORD_DUPLICATE: "duplicate:record",
  CONNECTION_UPDATE: "connection:update",
  CONNECTION_UPDATED: "connection:updated",
  CONNECTION_DELETE: "connection:delete",
  CONNECTION_DELETED: "connection:deleted",
  CONNECTION_EXPORT: "connection:export",
  CONNECTION_EXPORTED: "connection:exported",
  CONNECTION_IMPORT: "connection:import",
  CONNECTION_IMPORTED: "connection:imported",
  DATABASE_CREATE: "database:create",
  DATABASE_CREATED: "database:created",
  DATABASE_DROP: "database:drop",
  DATABASE_DROPPED: "database:dropped",
  COLLECTION_CREATE: "collection:create",
  COLLECTION_CREATED: "collection:created",
  COLLECTION_DROP: "collection:drop",
  COLLECTION_DROPPED: "collection:dropped",
});

export enum TYPE_LOGGER {
  CONNECT_MONGO_DB = "connectMongoDB",
}
